[package]
name = "service-bridge"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A placeholder."
homepage = "https://github.com/lenovo-it/service-bridge"
repository = "https://github.com/lenovo-it/service-bridge"
readme = "README.md"
